### ISSUE TITLE
Switching to Española throws console errors

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#105]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lukeocodes** [comment]
@alvaroartano want to look into this?

**Comment by alvaroartano** [comment]
I was looking for what it can be, but no idea
