### ISSUE TITLE
Fetch help-wanted issues as number from github API in netlify function

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#12]
When you add help-wanted to your repo issues, it appears on the repo cards.

<img width="346" alt="Screenshot 2020-10-11 at 13 22 39" src="https://user-images.githubusercontent.com/956290/95678527-23156680-0bc5-11eb-869f-6ec67909b26b.png">

Fetch the number of issues 'help-wanted && open' so we can replicate on our remote issue card, return it as a number from the Netlify function.

https://github.com/lukeocodes/hacktoberfest-checker/issues?q=label%3A%22help+wanted%22+is%3Aissue+is%3Aopen

**Comment by RascalTwo** [comment]
Hey, I could do this!

**Comment by lukeocodes** [comment]
check the README, it now has steps to get started locally
