### ISSUE TITLE
Allow user/repo format

### ISSUE THREAD

**Issue by nhcarrigan** [lukeocodes/hacktoberfest-checker#46]
Currently the project can only validate full urls (`https://github.com/igitalocean/hacktoberfest`). I propose adding the ability to pass in just `digitalocean/hacktoberfest` for validation as well.

**Comment by alhassanv** [comment]
If this is available to claim, I'm available!

**Comment by lukeocodes** [comment]
@alhassanv please go ahead :) My suggestion would be to validate it on the client, but only ever send through a URL to the server. The server has very robust URL validation, so a change of regex here would be cool

**Comment by charj** [comment]
Great idea.

**Comment by alhassanv** [comment]
@lukeocodes please close this issue :)
