### ISSUE TITLE
Discord bot using the same check-repository logic

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#49]
new endpoint and share validation and request logic with existing netlify function

**Comment by alhassanv** [comment]
Can you share more information? 
I've done discord bots with nodejs before but never embedded into a web application.

**Comment by lukeocodes** [comment]
It would need you to investigate hosting a discord bot on Netlify Functions @alhassanv. Netlify Functions are the same as AWS Lambda, if that helps. I will change this issue into Discord bot and make a separate Slack bot issue as that is the easier one.

**Comment by rishit-khandelwal** [comment]
can i make an bot for this purpose. i have some code which works: [hacktoberbot](https://github.com/rishit-khandelwal/hacktoberbot)

**Comment by mananchawla2005** [comment]
@lukeocodes I might be able to do this 🤔

**Comment by lukeocodes** [comment]
Closing this because it appears it is not possible using Netlify Functions.
