### ISSUE TITLE
change CheckRepository into a global component

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#53]
change `CheckRepository.vue` into a global component by moving it from `components/` to `components/global/`.

**Comment by gregorygregio** [comment]
Just move the file? No additional configuration is required to make it global?

**Comment by lukeocodes** [comment]
👍🏻

**Comment by lukeocodes** [comment]
@gregorygregio coorrrrrrect

**Comment by gregorygregio** [comment]
Alright! I will make the PR

**Comment by gregorygregio** [comment]
Thanks for the opportunity to contribute! Let me know if there is anything else I could do!
