### ISSUE TITLE
The site functionality should be unavailable on days that Hacktoberfest is not running (for 11 months of the year)

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#59]
# Feature Request

## Describe the solution you'd like

Display a different markdown driven content page when the event is closed.

## Additional context

Perhaps a 3rd page should be displayed in the month leading up to October.

**Comment by alvaroartano** [comment]
Can I try to do this? or are you managing yourself doing it?

**Comment by lukeocodes** [comment]
I was going to do this one :)

**Comment by alvaroartano** [comment]
oh ok 👍
