### ISSUE TITLE
Background color of the language option doesn't change for Dark Mode

### ISSUE THREAD

**Issue by shreyas44** [lukeocodes/hacktoberfest-checker#67]
**Describe the bug**
Background color of the language option doesn't change for Dark Mode

**Expected behavior**
The background color of the text to change

**Screenshots**
![Screen Shot 2020-10-21 at 6 36 38 PM](https://user-images.githubusercontent.com/46835608/96723715-888b0380-13cc-11eb-977a-53e266607307.png)
![Screen Shot 2020-10-21 at 6 36 42 PM](https://user-images.githubusercontent.com/46835608/96723726-8d4fb780-13cc-11eb-8e4b-8bfde775b118.png)
**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 86

**Comment by lukeocodes** [comment]
Go fix it @shreyas44 :D
