### ISSUE TITLE
client side URL validation

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#7]
add validation in the `CheckRepository.vue` component

**Comment by Giotje** [comment]
I'll check this one!

**Comment by lukeocodes** [comment]
@Giotje check out how I did it in the Netlify function `functions/check-repository/check-repository.js`. This might be helpful. 

I'm not sure [the URL interface](https://developer.mozilla.org/en-US/docs/Web/API/URL) can gracefully tell you when something isn't valid.

I've previously made a method that catches the error thrown by URL and `return false`, otherwise it's true`. Up to you how you make it though!

**Comment by charj** [comment]
Jumping on this

**Comment by charj** [comment]
Sorted.
https://github.com/lukeocodes/hacktoberfest-checker/pull/44
https://github.com/lukeocodes/hacktoberfest-checker/pull/45
