### ISSUE TITLE
Française translation following CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#70]
# Feature Request

## Describe the solution you'd like

Following the `CONTRIBUTING.md` section on translations provide a Française translation.

- [ ] `README.md` -> `.github/lang/README.fr.md`
- [ ] `CONTRIBUTING.md` -> `.github/lang/CONTRIBUTING.fr.md`
- [ ] `lang/en.js` -> `lang/fr.js`
- [ ] `content/en/index.md` -> `content/fr/index.md`
- [ ] `content/en/details.md` -> `content/fr/details.md`

**Comment by lukeocodes** [comment]
Hey @Pandz18 did you want me to assign this to you?

**Comment by Pandz18** [comment]
> Hey @Pandz18 did you want me to assign this to you?

Hi sure you can but I have to translate only the ReadMe file and the contributing file , if I'm not wrong ?

**Comment by Pandz18** [comment]
or all the files that have empty boxes next to them in your first comment

**Comment by lukeocodes** [comment]
You can do just the docs if you like, but there is a chance to add French to the site translations too (all the files listed). I can explain how to do this and how to test it, if you like :) 

![image](https://user-images.githubusercontent.com/956290/97077933-bd22d900-15df-11eb-8a56-44eee30bd764.png)

**Comment by Pandz18** [comment]
> You can do just the docs if you like, but there is a chance to add French to the site translations too (all the files listed). I can explain how to do this and how to test it, if you like :)
> 
> ![image](https://user-images.githubusercontent.com/956290/97077933-bd22d900-15df-11eb-8a56-44eee30bd764.png)

Hi , I did it for all of them , also my PR is showing an error. Can you tell me what I did wrong

**Comment by Pandz18** [comment]
@lukeocodes  Hi , I apologise for this but I've added a profile pic and was wondering if you could update it ? If it's not much of an issue .

**Comment by Pandz18** [comment]
@lukeocodes I apologise but this will be the last time I request you to update my photo, I'm so sorry but my mum told me to change my pfp . I'm so sorry Jaden for disturbing
