### ISSUE TITLE
Deutsch translation following CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#71]
# Feature Request

## Describe the solution you'd like

Following the `CONTRIBUTING.md` section on translations provide a Deutsch translation.

- [ ] `README.md` -> `.github/lang/README.de.md`
- [ ] `CONTRIBUTING.md` -> `.github/lang/CONTRIBUTING.de.md`
- [ ] `lang/en.js` -> `lang/de.js`
- [ ] `content/en/index.md` -> `content/de/index.md`
- [ ] `content/en/details.md` -> `content/de/details.md`

**Comment by wrunkel** [comment]
I would like to work on this issue.

**Comment by lukeocodes** [comment]
All yours :) let me know if you have any questions
