### ISSUE TITLE
Española translation following CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#75]
# Feature Request

## Describe the solution you'd like

Following the `CONTRIBUTING.md` section on translations provide a Española translation.

- [x] `README.md` -> `.github/lang/README.es.md`
- [x] `CONTRIBUTING.md` -> `.github/lang/CONTRIBUTING.es.md`
- [ ] `lang/en.js` -> `lang/es.js`
- [ ] `content/en/index.md` -> `content/es/index.md`
- [ ] `content/en/details.md` -> `content/es/details.md`

**Comment by lukeocodes** [comment]
@alvaroartano FYI

**Comment by alvaroartano** [comment]
Perfect! I'll start translating it now, and probably open a PR with the /lang/es.js translation today. I will open another PR with the translation of the content folder tomorrow.

**Comment by lukeocodes** [comment]
One PR, please 🙏

**Comment by alvaroartano** [comment]
Okay, I will do it like that 👍
