### ISSUE TITLE
हिंदी translation following CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#77]
# हिंदी translation following CONTRIBUTING.md

## Describe the solution you'd like

Following the `CONTRIBUTING.md` section on translations provide a हिंदी translation.

- [ ] `README.md` -> `.github/lang/README.hi.md`
- [ ] `CONTRIBUTING.md` -> `.github/lang/CONTRIBUTING.hi.md`
- [ ] `lang/en.js` -> `lang/hi.js`
- [ ] `content/en/index.md` -> `content/hi/index.md`
- [ ] `content/en/details.md` -> `content/hi/details.md`

**Comment by sudiptog81** [comment]
Can take on this one.
