### ISSUE TITLE
Português translation following CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#79]
# Português translation following CONTRIBUTING.md

## Describe the solution you'd like

Following the `CONTRIBUTING.md` section on translations provide a Português translation.

- [ ] `README.md` -> `.github/lang/README.pt.md`
- [ ] `CONTRIBUTING.md` -> `.github/lang/CONTRIBUTING.pt.md`
- [ ] `lang/en.js` -> `lang/pt.js`
- [ ] `content/en/index.md` -> `content/pt/index.md`
- [ ] `content/en/details.md` -> `content/pt/details.md`

**Comment by LetticiaNicoli** [comment]
Hi @lukeocodes, I'll work on this 😄   🇧🇷

**Comment by saxocat** [comment]
Hey @LetticiaNicoli ! Is possible for you to work on the last 3 topics? I've already translated 1 and 2 and sent a pull request. Thank you! 🇵🇹

**Comment by LetticiaNicoli** [comment]
@saxocat no prob, I'll take a look in your PR and translate the missing topics.
thanks for sharing ☺️
