### ISSUE TITLE
Checking - https://github.com/Nexmo/nexmo-developer returns a 500 error

### ISSUE THREAD

**Issue by GregHolmes** [lukeocodes/hacktoberfest-checker#82]
**Describe the bug**
When you try to check whether a certain repository is enabled for Hacktoberfest event, a 500 error was returned. On inspecting the preview of the Console, you can see that the response is a 403 / FORBIDDEN

**To Reproduce**

1. Go to: https://hacktoberfest.ninja/checker
2. Enter: https://github.com/Nexmo/nexmo-developer and submit
3. See error: `Request failed with status code 500`

**Expected behavior**
The expected behaviour is to see the confirmation of whether the repository is a part of Hacktoberfest or not.

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.7
- Browser: Chrome
- Version 86.0.4240.80

**Comment by lukeocodes** [comment]
Yes, was that SSO wasn't enabled on my personal access token. Fixed
