### ISSUE TITLE
Add link to this repo on the website

### ISSUE THREAD

**Issue by shreyas44** [lukeocodes/hacktoberfest-checker#83]
# Feature Request

## Is your feature request related to a problem? Please describe:

Not really a problem, but anyone who visits the site doesn't know it's open source and it would be nice if there was a link to this GitHub repo.

## Describe the solution you'd like

Add a GitHub logo which links to this repo.

## Additional context

![Screen Shot 2020-10-23 at 2 16 23 AM](https://user-images.githubusercontent.com/46835608/96928142-c293fc80-14d5-11eb-97c5-a0d573dc5838.png)
The logo could be towards the right of the language selector.

**Comment by lukeocodes** [comment]
Good idea :) maybe in the footer too!
