### ISSUE TITLE
CSS formatting of errors

### ISSUE THREAD

**Issue by lukeocodes** [lukeocodes/hacktoberfest-checker#9]
format the error output in `CheckRepository.vue` component

**Comment by leobia** [comment]
Hi! I wanted to help you on this issue, but I'm not understanding how to run `functions\check-repository` from a local environment (I'm a newbie with nuxt.js).

I'm seeing that a request is sent a this url:
```http://localhost:8888/api/check-repository```

But `npm run dev` doesn't start anuthing on that port. Am I missing something?

**Comment by lukeocodes** [comment]
Hi please see the README which has now been updated to help you test the API calls on your local machine
